### ISSUE TITLE
Really simple schema not working

### ISSUE THREAD

**Issue by Greedquest** [asottile/cfgv#89]
I was wondering if you might be able to take a look? Sorry, this seems so basic but I can't figure it out:

```python
from __future__ import annotations

import cfgv
import toml
import pprint


def loads_config(
    schema,
    value: str,
    ctx: str | None = "RAW_STRING",
    exc_tp=cfgv.ValidationError,
) -> dict:
    with cfgv.reraise_as(exc_tp):
        with cfgv.validate_context(f"In {ctx}"):
            try:
                data = toml.loads(value)
            except Exception as e:
                raise cfgv.ValidationError(f"{type(e).__name__!s}: {e!s}")
            pprint.pprint(data)
            cfgv.validate(data, schema)
            return cfgv.apply_defaults(data, schema)


PROJECT_SCHEMA = cfgv.Map(
    "project",
    "id",
    cfgv.Required("id", cfgv.check_string),  # TODO REGEX here
    cfgv.Optional("files", cfgv.check_text, r"\.(bas|cls)$"),
)


def main() -> int:
    config = """
    [project]
    id = "test-id"
    """

    parsed = loads_config(PROJECT_SCHEMA , config) #errors here
    print(parsed)


if __name__ == "__main__":
    raise SystemExit(main())
```

That keeps giving the following as if I'm not specifying the id

```
ValidationError: 
=====> 
==> In RAW_STRING
==> At project(id=MISSING)
=====> Missing required key: id
```

What obvious thing am I doing wrong?

**Comment by Greedquest** [comment]
@asottile Sorry I didn't include as I assumed I was just using the lib wrong. Here it is:

```
> python -m test
{'project': {'id': 'test-id'}}
Traceback (most recent call last):
  File "C:\Users\[username]\anaconda3\envs\viv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[username]\anaconda3\envs\viv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Github\viv\viv\scratchpad.py", line 44, in <module>
    raise SystemExit(main())
  File "C:\Github\viv\viv\scratchpad.py", line 39, in main
    parsed = loads_config(PROJECT_SCHEMA, config)  # errors here
  File "C:\Github\viv\viv\scratchpad.py", line 22, in loads_config
    return cfgv.apply_defaults(data, schema)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "C:\Github\viv\viv\scratchpad.py", line 22, in loads_config
    return cfgv.apply_defaults(data, schema)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 31, in validate_context
    yield
  File "C:\Github\viv\viv\scratchpad.py", line 21, in loads_config
    cfgv.validate(data, schema)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 376, in validate
    schema.check(v)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 244, in check
    item.check(v)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 31, in validate_context
    yield
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 244, in check
    item.check(v)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 72, in _check_required
    _require_key(self, dct)
  File "C:\Users\[username]\anaconda3\envs\viv\lib\site-packages\cfgv.py", line 68, in _require_key
    raise ValidationError(f'Missing required key: {self.key}')
cfgv.ValidationError:
=====>
==> In RAW_STRING
==> At project(id=MISSING)
=====> Missing required key: id
```

This wis Win 11
```
# Name                    Version                   Build  Channel
python                    3.9.7                h6244533_1
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
```
